name: Build
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: |
          wget -nv https://golang.org/dl/go1.21.5.linux-amd64.tar.gz \
          && sudo rm -rf /usr/local/go \
          && sudo rm -rf m -rf /usr/bin/go \
          && sudo tar -C /usr/local -xzf go1.21.5.linux-amd64.tar.gz \
          && export PATH=$PATH:/usr/local/go/bin \
          && go version
      - name: Build
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV 
          TAG="${GITHUB_REF#refs/tags/}"
          HASH=$(git log -n1 --pretty=format:%h)
          echo ${TAG} ${HASH}
          export PATH=$PATH:/usr/local/go/bin \
          && env GOOS=linux CGO_ENABLED=0 GOARCH=amd64 go build -o resetns \
          && cp resetns resetns_Linux_x86_64 && tar -cvzf resetns_Linux_x86_64.tar.gz resetns && rm -rf resetns \
          && env GOOS=linux CGO_ENABLED=0 GOARCH=arm64 go build -o resetns \
          && tar -cvzf resetns_Linux_arm64.tar.gz resetns && cp resetns_Linux_arm64.tar.gz resetns_Linux_aarch64.tar.gz && rm -rf resetns \
          && env GOOS=darwin CGO_ENABLED=0 GOARCH=amd64 go build -o resetns \
          && cp resetns resetns_Darwin_x86_64 && tar -cvzf resetns_Darwin_x86_64.tar.gz resetns && rm -rf resetns \
          && env GOOS=darwin CGO_ENABLED=0 GOARCH=arm64 go build -o resetns \
          && tar -cvzf resetns_Darwin_arm64.tar.gz resetns && cp resetns_Darwin_arm64.tar.gz resetns_Darwin_aarch64.tar.gz && rm -rf resetns \
          && env GOOS=windows CGO_ENABLED=0 GOARCH=amd64 go build -o resetns.exe \
          && zip resetns_Windows_x86_64.zip resetns.exe \
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            checksums.txt
            resetns_Linux_x86_64
            resetns_Linux_x86_64.tar.gz 
            resetns_Darwin_x86_64
            resetns_Darwin_x86_64.tar.gz
            resetns_Windows_x86_64.zip
          name: "${{ env.RELEASE_TAG }} release"